name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: stoked-citizen-444921-v7

    # 3. Build and push Docker image to Google Container Registry
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/stoked-citizen-444921-v7/fastapi-service

    # 4. Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-service \
          --image gcr.io/stoked-citizen-444921-v7/fastapi-service \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
