name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: stoked-citizen-444921-v7
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-service \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
